name: todo_note_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.0
  flutter_hooks: ^0.18.6
  flutter_riverpod: ^2.3.6
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.7
  go_router: ^9.0.2
  google: ^0.0.1
  google_sign_in: ^6.1.4
  graphql: ^5.1.3
  graphql_codegen: null
  graphql_flutter: ^5.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_serializable: null
  path_provider: ^2.0.15
  uuid: ^3.0.7

dev_dependencies:
  build_runner: null
  flutter_gen: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: null

flutter:

  uses-material-design: true

  assets:
    - assets/graphql/
    - assets/images/
    - lib/
